name: todo
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  #  dependency injection
  get_it: ^8.2.0

  #  mapper
  equatable: ^2.0.7
  flutter_dotenv: ^6.0.0
  dartz: ^0.10.1

  #  navigation and routing
  go_router: ^16.2.1

  #   internationalized/localized, date and number formatting and parsing
  intl: ^0.20.2

  #  responsive
  flutter_screenutil: ^5.9.3

  #  svg
  flutter_svg: ^2.2.1

  #  text font family
  google_fonts: ^6.3.1

  #  local storage
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2

  #  phone number formatter
  flutter_multi_formatter: ^2.13.10

  #  animation
  animated_dropdown_search_codespark: ^2.2.0
  flutter_staggered_animations: ^1.1.1

  # localization
  easy_localization: ^3.0.8
  image_picker: ^1.2.0
  #  secure storage
  flutter_secure_storage: ^10.0.0-beta.4
  cupertino_icons: ^1.0.8

  #  painting
  flutter_colorpicker: ^1.1.0
  toastification: ^3.0.3
  # state management
  flutter_bloc: ^9.1.1
  logger: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true
fonts:
  - family: Manrope
    fonts:
      - asset: assets/fonts/Manrope/Static/Manrope-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Manrope/Static/Manrope-Bold.ttf
        weight: 700
      - asset: assets/fonts/Manrope/Static/Manrope-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Manrope/Static/Manrope-Medium.ttf
        weight: 500
      - asset: assets/fonts/Manrope/Static/Manrope-Regular.ttf
        weight: 400
      - asset: assets/fonts/Manrope/Static/Manrope-Light.ttf
        weight: 300
      - asset: assets/fonts/Manrope/Static/Manrope-ExtraLight.ttf
        weight: 200
  - family: Roboto
    fonts:
      - asset: assets/fonts/Manrope/Manrope-VariableFont_wght.ttf